# Generated by Django 3.0.2 on 2020-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_no_verified',
            field=models.BooleanField(default=False),
        ),
    ]
