# Generated by Django 3.0.2 on 2020-02-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20200131_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('M', 'Manufacturer'), ('D', 'Distributer'), ('W', 'Wholesaler'), ('P', 'Pharmacy'), ('C', 'Customer')], default='C', max_length=3),
        ),
    ]
